import fs from "fs-extra";
import path from "path";
import { parse } from "csv-parse/sync";
import smartypants from "smartypants";

// Load profanity patterns (your own list)
import profanityPatterns from "../profanity_patterns.json";

interface Row {
  time: string;
  quote_time: string;
  quote: string;
  title: string;
  author: string;
  nsfw_overwrite: string;
}

interface OutputRow {
  time: string;
  quote_first: string;
  quote_time_case: string;
  quote_last: string;
  title: string;
  author: string;
  sfw: string;
}

// Try project root first, then src/data
const CSV_CANDIDATES = [
  path.resolve(process.cwd(), 'litclock_annotated.csv'),
  path.resolve(process.cwd(), 'src', 'data', 'litclock_annotated.csv'),
];

function findCsvPath(): string | null {
  for (const p of CSV_CANDIDATES) if (fs.existsSync(p)) return p
  return null
}

async function main() {
  const csvPath = findCsvPath()
  if (!csvPath) {
    throw new Error(`CSV file not found. Checked: ${CSV_CANDIDATES.join(', ')}`)
  }

  const raw = fs.readFileSync(csvPath, "utf8");
  const lines = raw.split("\n").length;

  const records: Row[] = parse(raw, {
    delimiter: "|",
    // disable CSV quoting so unescaped quotes inside fields won't break parsing
    quote: "\0",
    trim: true,
    skip_empty_lines: true,
    columns: ["time", "quote_time", "quote", "title", "author", "nsfw_overwrite"],
  });

  if (records.length !== lines) {
    console.warn("Warning: CSV row count mismatch");
  }

  // Build regex for profanity
  const profanityList: string[] = (profanityPatterns as unknown) as string[];
  const profanityRegex =
    profanityList && profanityList.length > 0
      ? new RegExp(`\\b(${profanityList.map(escapeRegex).join("|")})\\b`, "i")
      : /$a/; // never matches when list is empty

  const processed: OutputRow[] = records.map((row) => {
    const auto_nsfw = profanityRegex.test(row.quote);
    const nsfw =
      row.nsfw_overwrite === "nsfw" ||
      (auto_nsfw && row.nsfw_overwrite !== "sfw");

    const sfw = nsfw ? "no" : "yes";

    // Smart punctuation
    const quote = smartypants(row.quote).trim();
    const quoteTime = smartypants(row.quote_time).trim();

    // Split quote around quote_time
    const timeRegex = new RegExp(
      `(?<!\\w)${escapeRegex(quoteTime)}(?!\\w)`,
      "i"
    );

    const match = quote.match(timeRegex);
    if (!match) {
      throw new Error(`Parsing error for quote_time: ${quoteTime}`);
    }

    const [quote_first, quote_last] = quote.split(timeRegex);
    const quote_time_case = match[0];

    return {
      time: row.time,
      quote_first,
      quote_time_case,
      quote_last,
      title: row.title,
      author: row.author,
      sfw,
    };
  });

  // Group by time
  const grouped: Record<string, OutputRow[]> = {};
  for (const row of processed) {
    if (!grouped[row.time]) grouped[row.time] = [];
    grouped[row.time].push(row);
  }

  for (const time of Object.keys(grouped)) {
    const filename = time.replace(":", "_") + ".json";
  }

  // Also generate a TypeScript module with a single random quote per minute
  const timeQuotesDir = path.resolve(process.cwd(), 'src', 'constants');
  await fs.mkdirp(timeQuotesDir);

  // produce entries for each minute of the day (00:00..23:59)
  const perMinute: { time: string; text: string; author?: string, title?: string }[] = [];
  for (let h = 0; h < 24; h++) {
    for (let m = 0; m < 60; m++) {
      const key = `${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}`;
      const bucket = grouped[key];
      if (bucket && bucket.length > 0) {
        const pick = bucket[Math.floor(Math.random() * bucket.length)];
        const fullText = `${pick.quote_first}${pick.quote_time_case}${pick.quote_last}`.trim();
        perMinute.push({ time: key, text: fullText, author: pick.author || undefined, title: pick.title || undefined });
      }
    }
  }

  const timeQuotesPath = path.join(timeQuotesDir, 'TimeQuotes.ts');
  if (fs.existsSync(timeQuotesPath)) await fs.remove(timeQuotesPath);

  const outLines: string[] = [];
  outLines.push('// AUTOGENERATED by src/data/utils/convert.ts — do not edit');
  outLines.push('export interface TimeQuote { time: string; text: string; author?: string, title?: string }');
  outLines.push('export const QUOTES: TimeQuote[] = [');
  for (const q of perMinute) {
    outLines.push(`  { time: ${JSON.stringify(q.time)}, text: ${JSON.stringify(q.text)}, author: ${q.author ? JSON.stringify(q.author) : 'undefined'}, title: ${q.title ? JSON.stringify(q.title) : 'undefined'} },`);
  }
  outLines.push(']');
  outLines.push('');

  await fs.writeFile(timeQuotesPath, outLines.join('\n'), 'utf8');

  console.log('Done! Wrote JSON files and', timeQuotesPath);
}

function escapeRegex(str: string) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

main().catch(console.error);
